# Generated by Django 5.0.1 on 2024-02-07 23:22

import django.core.validators
import django.db.models.deletion
import games_journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo')], max_length=20)),
                ('hours_played', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('year_played', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1960), games_journal.models.max_value_current_year])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamehistory',
            },
        ),
        migrations.AddConstraint(
            model_name='gamehistory',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating'),
        ),
        migrations.AddConstraint(
            model_name='gamehistory',
            constraint=models.CheckConstraint(check=models.Q(('platform__in', ['PC', 'PlayStation', 'Xbox', 'Nintendo'])), name='valid_platform'),
        ),
        migrations.AddConstraint(
            model_name='gamehistory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_game_for_user'),
        ),
    ]
